@echo off
:: -------------------------------------------------------------
:: Project: DataValuator
:: Authored and generated by: Shaurya Singh
:: -------------------------------------------------------------
echo =========================================
echo    Stopping DataValuator Environment
echo =========================================
echo.

echo Stopping backend and frontend servers...
:: Kills any command prompt window that starts with "DataValuator" and all of its child processes (node, python, etc.)
taskkill /FI "WINDOWTITLE eq DataValuator*" /T /F >nul 2>&1

echo.
echo Servers have been successfully stopped!
echo.
pause
